### ISSUE TITLE
游玩关卡的左边墙壁上面有一部分没有碰撞，可以直接跳出去

### ISSUE THREAD

**Issue by Fujige** [Asixa/Steam-Multiplayer-for-Unity#2]

**Comment by Asixa** [comment]
这只是个demo...........

**Comment by Fujige** [comment]
我知道啊，我是说可以碰撞体可以再拉高点




------------------ 原始邮件 ------------------
发件人: "Asixa"<notifications@github.com>;
发送时间: 2018年3月6日(星期二) 晚上8:26
收件人: "Asixa/Steam-Multiplayer-for-Unity"<Steam-Multiplayer-for-Unity@noreply.github.com>;
抄送: "Halo"<450580217@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Asixa/Steam-Multiplayer-for-Unity] 游玩关卡的左边墙壁上面有一部分没有碰撞，可以直接跳出去 (#2)




这只是个demo...........

**Comment by Asixa** [comment]
已修复
